# Generated by Django 4.2.3 on 2023-07-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='password',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
